project:
  type: website
  render:
    - "*.qmd"
    - "projects/**/*.qmd"

website:
  title: "Léo Gouzy"
  site-url: "https://leogoose31.github.io/portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: Parcours
      - href: projects/index.qmd
        text: Projets
    background: light
    border: true

format:
  html:
    theme:
      - default
      - custom.scss
    toc: false
