<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Prévoir le chiffre d’affaires d’un restaurant, jour par jour – Léo Gouzy</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-091c3cd4ae248224db46d09edee246ef.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c8eae255f88ecd4c9eb77aee7309cd87.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta property="og:title" content="Prévoir le chiffre d’affaires d’un restaurant, jour par jour – Léo Gouzy">
<meta property="og:description" content="Un modèle XGBoost entraîné sur le journal de caisse pour transformer un prévisionnel statique en outil de pilotage opérationnel. Mémoire DSCG, 2023.">
<meta property="og:image" content="https://leogoose31.github.io/portfolio/projects/memoire-dscg-ia-previsions/img/fig-jeu-de-donnees.png">
<meta property="og:site_name" content="Léo Gouzy">
<meta property="og:image:alt" content="Série temporelle du chiffre d'affaires journalier de 2018 à 2023, montrant deux interruptions Covid et une hausse de niveau à partir de mi-2022.">
<meta property="og:image:height" content="422">
<meta property="og:image:width" content="1219">
<meta name="twitter:title" content="Prévoir le chiffre d’affaires d’un restaurant, jour par jour – Léo Gouzy">
<meta name="twitter:description" content="Un modèle XGBoost entraîné sur le journal de caisse pour transformer un prévisionnel statique en outil de pilotage opérationnel. Mémoire DSCG, 2023.">
<meta name="twitter:image" content="https://leogoose31.github.io/portfolio/projects/memoire-dscg-ia-previsions/img/fig-jeu-de-donnees.png">
<meta name="twitter:image:alt" content="Série temporelle du chiffre d'affaires journalier de 2018 à 2023, montrant deux interruptions Covid et une hausse de niveau à partir de mi-2022.">
<meta name="twitter:image-height" content="422">
<meta name="twitter:image-width" content="1219">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Léo Gouzy</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Accueil</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">Parcours</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects/index.html"> 
<span class="menu-text">Projets</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/léo-gouzy-013a65151" target="_blank"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/leogoose31" target="_blank"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:leogouzy31@gmail.com"> <i class="bi bi-envelope" role="img" aria-label="Email">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Prévoir le chiffre d’affaires d’un restaurant, jour par jour</h1>
<p class="subtitle lead">Un modèle XGBoost entraîné sur le journal de caisse pour transformer un prévisionnel statique en outil de pilotage opérationnel. Mémoire DSCG, 2023.</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="projet-meta">
<p><span class="tag">Python</span> <span class="tag">XGBoost</span> <span class="tag">Optuna</span> <span class="tag">Séries temporelles</span> <span class="tag">Feature engineering</span></p>
</div>
<section id="le-problème" class="level2">
<h2 class="anchored" data-anchor-id="le-problème">Le problème</h2>
<p>Le prévisionnel comptable « classique » repose sur des moyennes, une hypothèse de marge constante et une granularité mensuelle, voire annuelle. Il suppose que demain ressemblera à hier : il ne capte ni la saisonnalité fine d’une activité, ni les jours de la semaine, et reste exposé aux erreurs de jugement humain. Daniel Kahneman en distingue deux : le <strong>biais</strong> (se tromper toujours dans le même sens) et le <strong>bruit</strong> (deux personnes, mêmes chiffres, prévisions différentes).</p>
<p>La question posée par le mémoire : peut-on prévoir le chiffre d’affaires <strong>journalier</strong> d’un restaurant à partir de ses seules données comptables, avec une précision suffisante pour en faire un outil de pilotage — achats, stocks, plannings ? L’enjeu est double, économique et environnemental : mieux anticiper, c’est acheter au plus juste et moins jeter.</p>
<div class="en-clair">
<p><strong>En clair —</strong> un prévisionnel comptable traditionnel dit « le mois prochain, environ X ». Ici, on cherche à dire « samedi prochain, environ Y » — assez précis pour qu’un restaurateur sache combien commander et combien de personnes faire travailler.</p>
</div>
</section>
<section id="les-données" class="level2">
<h2 class="anchored" data-anchor-id="les-données">Les données</h2>
<p>Point de départ : la caisse informatisée du client. Les encaissements sont détaillés par jour et ventilés par taux de TVA, puis remontés via une API. C’est ce <strong>journal de caisse</strong>, du <strong>01/04/2018 au 30/03/2023</strong> et entièrement <strong>anonymisé</strong>, qui a servi de base d’entraînement.</p>
<p>Choix assumé : prédire le chiffre d’affaires <strong>à partir de lui-même</strong>, sans donnée externe. À cette granularité, aucune source météo ou sectorielle n’a été jugée assez pertinente pour justifier sa complexité. Le nettoyage a consisté à retirer les jours de fermeture — repos hebdomadaire et fermetures administratives Covid — repérés en traçant la série.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig-jeu-de-donnees.png" class="img-fluid figure-img" alt="Série temporelle du chiffre d'affaires journalier de 2018 à 2023, montrant deux interruptions Covid et une hausse de niveau à partir de mi-2022."></p>
<figcaption>Le chiffre d’affaires journalier de 2018 à 2023. Les deux paliers plats correspondent aux fermetures Covid ; le niveau grimpe nettement à partir de mi-2022.</figcaption>
</figure>
</div>
<div class="en-clair">
<p><strong>En clair —</strong> la matière première n’est pas un fichier de data science tout prêt : c’est la caisse réelle d’un vrai restaurant. Une bonne partie du travail est de la rendre exploitable sans trahir les chiffres.</p>
</div>
</section>
<section id="lapproche" class="level2">
<h2 class="anchored" data-anchor-id="lapproche">L’approche</h2>
<pre><code>Journal de caisse — CA journalier par TVA (2018 → 2023)
    └── Python (pandas)
            ├── nettoyage           — retrait des jours fermés (repos, Covid)
            ├── détection de rupture — lib « ruptures », point au 23/07
            ├── Optimal Transport    — réalignement des deux régimes de CA
            ├── feature engineering  — 2 → 16 variables calendaires
            ├── target encoding      — sous cross-validation (anti-fuite)
            └── XGBoost + Optuna      — split temporel 90 / 10</code></pre>
<section id="détection-de-rupture-et-optimal-transport" class="level3">
<h3 class="anchored" data-anchor-id="détection-de-rupture-et-optimal-transport">Détection de rupture et Optimal Transport</h3>
<div class="bloc-technique">
<p>Technique</p>
</div>
<p>La visualisation révèle deux régimes de chiffre d’affaires séparés par un point de rupture, détecté automatiquement avec la bibliothèque <code>ruptures</code> (au 23 juillet). Entraîner un modèle sur une série qui « change de niveau » en cours de route le fausse. J’ai donc réaligné la distribution antérieure via l’<strong>Optimal Transport</strong> — un procédé mathématique qui mesure le « coût » pour transformer une distribution en une autre, et déplace ici les valeurs anciennes vers le niveau récent. Sans ce réalignement, le modèle sous-évaluait systématiquement les données de test.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig-optimal-transport.png" class="img-fluid figure-img" alt="Graphique montrant les données originales en bleu et les mêmes données transportées vers le haut en rouge après Optimal Transport."></p>
<figcaption>L’Optimal Transport relève la période antérieure au 23 juillet (en bleu) au niveau du régime récent (en rouge), pour homogénéiser la série d’entraînement.</figcaption>
</figure>
</div>
<div class="en-clair">
<p><strong>En clair —</strong> à un moment, le restaurant a durablement changé de niveau d’activité (nouvelle carte, notoriété, travaux…). Apprendre sur « l’ancien » et « le nouveau » mélangés brouille tout. L’Optimal Transport remet l’ancienne période à l’échelle de la nouvelle, pour que le modèle apprenne sur une histoire cohérente.</p>
</div>
</section>
<section id="feature-engineering-de-2-à-16-colonnes" class="level3">
<h3 class="anchored" data-anchor-id="feature-engineering-de-2-à-16-colonnes">Feature engineering : de 2 à 16 colonnes</h3>
<div class="bloc-technique">
<p>Technique</p>
</div>
<p>Le jeu de départ ne contient que deux colonnes : date et chiffre d’affaires. J’en ai dérivé quatorze variables <strong>calendaires</strong> : jour de la semaine, week-end (oui/non), jour de l’année, numéro de semaine, position en début ou fin de mois, etc. C’est le cœur de la performance : ce ne sont pas les chiffres bruts qui font la prévision, mais ces repères temporels que le modèle apprend à associer aux hausses et aux baisses.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig-saisonnalite-hebdo.png" class="img-fluid figure-img" alt="Série du chiffre d'affaires sur un mois montrant une nette périodicité hebdomadaire, avec des pics le week-end."></p>
<figcaption>Zoom sur un mois : la structure hebdomadaire saute aux yeux, avec des pics réguliers de week-end. C’est exactement ce que les variables calendaires permettent au modèle de capter.</figcaption>
</figure>
</div>
<div class="en-clair">
<p><strong>En clair —</strong> une date seule (« 2023-07-15 ») ne dit rien à un modèle. En la décomposant en « samedi », « mi-juillet », « milieu de mois », on lui donne les indices qu’un gérant utilise intuitivement pour savoir si la journée sera chargée.</p>
</div>
</section>
<section id="encodage-cible-sans-fuite-de-données" class="level3">
<h3 class="anchored" data-anchor-id="encodage-cible-sans-fuite-de-données">Encodage cible sans fuite de données</h3>
<div class="bloc-technique">
<p>Technique</p>
</div>
<p>Les variables catégorielles (le mois, par exemple) sont remplacées par la moyenne du chiffre d’affaires associé — un <em>target encoding</em>. Le piège classique est la <strong>fuite de données</strong> : si l’on calcule cette moyenne sur l’ensemble des données, le modèle « voit » indirectement la réponse qu’il est censé deviner. Pour l’éviter, l’encodage est réalisé <strong>sous validation croisée</strong> : chaque portion de données est encodée à partir des autres, jamais d’elle-même.</p>
<div class="en-clair">
<p><strong>En clair —</strong> on veut noter le modèle sur des jours qu’il n’a jamais vus. Si on le laisse tricher en regardant les réponses pendant qu’il révise, sa note ne veut plus rien dire. La validation croisée l’empêche de tricher.</p>
</div>
</section>
<section id="le-modèle-gradient-boosting-puis-xgboost" class="level3">
<h3 class="anchored" data-anchor-id="le-modèle-gradient-boosting-puis-xgboost">Le modèle : Gradient Boosting, puis XGBoost</h3>
<div class="bloc-technique">
<p>Technique</p>
</div>
<p>Le <strong>Gradient Boosting</strong> construit une série de petits modèles (des arbres de décision) où chacun corrige l’erreur du précédent. On part de la moyenne des ventes ; on calcule l’écart avec le réel (le <em>résidu</em>) ; un arbre apprend à prédire cet écart à partir des variables calendaires ; on ajuste la prévision d’une fraction de cet écart (le <em>taux d’apprentissage</em>), et on recommence.</p>
<blockquote class="blockquote">
<p>Exemple : prévision de départ 1 000 €, réel 1 200 € → résidu de 200 €. Avec un taux d’apprentissage de 0,2, la nouvelle prévision devient 1 000 + (0,2 × 200) = <strong>1 040 €</strong>. On s’approche, arbre après arbre.</p>
</blockquote>
<p>Parmi les implémentations, le choix est raisonné : Gradient Boosting Machine (trop simple), LightGBM (taillé pour les très gros volumes, inadapté à un jeu de données restreint), puis <strong>XGBoost</strong> — retenu pour sa régularisation intégrée contre le surajustement et sa parallélisation. Les hyperparamètres ont été optimisés automatiquement avec <strong>Optuna</strong> :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Hyperparamètre</th>
<th>Rôle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>learning_rate</code></td>
<td>Part de chaque arbre dans la prévision finale — plus faible = plus fin, mais plus d’arbres</td>
</tr>
<tr class="even">
<td><code>n_estimators</code></td>
<td>Nombre d’arbres — trop élevé = risque de surapprentissage</td>
</tr>
<tr class="odd">
<td><code>max_depth</code></td>
<td>Profondeur des arbres — profond = capte le détail, mais surapprend</td>
</tr>
<tr class="even">
<td><code>subsample</code></td>
<td>Part des données utilisée par arbre — bride la spécialisation excessive</td>
</tr>
</tbody>
</table>
<p>Le découpage entraînement / test est <strong>temporel</strong> (90 / 10), jamais aléatoire : dans une série chronologique, mélanger le passé et le futur reviendrait à s’entraîner sur des jours postérieurs à ceux qu’on prétend prédire.</p>
<div class="en-clair">
<p><strong>En clair —</strong> le modèle avance par petites corrections successives, comme un tireur qui ajuste sa visée à chaque essai. Optuna se charge de régler les molettes du modèle à notre place, et on teste toujours sur la période la plus récente — celle qu’il n’a pas vue.</p>
</div>
</section>
</section>
<section id="le-résultat" class="level2">
<h2 class="anchored" data-anchor-id="le-résultat">Le résultat</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Métrique</th>
<th>Entraînement</th>
<th>Test</th>
<th>Global</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MAE</td>
<td>90 €</td>
<td>219 €</td>
<td>103 €</td>
</tr>
<tr class="even">
<td>RMSE</td>
<td>118 €</td>
<td>290 €</td>
<td>144 €</td>
</tr>
</tbody>
</table>
<p>Sur les données de test — jamais montrées au modèle — le chiffre d’affaires journalier est prédit avec une <strong>erreur moyenne d’environ 219 €</strong> (MAE). La RMSE, qui pénalise davantage les gros écarts, monte à 290 € : signe que la plupart des jours sont bien prédits, mais que quelques-uns le sont franchement mal. Et comme les erreurs sont plus faibles à l’entraînement qu’au test, le modèle est <strong>partiellement surajusté</strong> — je le diagnostique sans le masquer.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig-resultat-xgboost.png" class="img-fluid figure-img" alt="Graphique comparant les ventes réelles en bleu et les prévisions XGBoost en rouge, avec une ligne verticale séparant entraînement et test."></p>
<figcaption>Ventes réelles (bleu) contre prévisions du modèle XGBoost (rouge). La ligne verticale sépare les données d’entraînement (à gauche) des données de test (à droite) ; la partie finale prolonge la prévision au-delà des données disponibles.</figcaption>
</figure>
</div>
<div class="en-clair">
<p><strong>En clair —</strong> en moyenne, le modèle se trompe de ~219 € par jour sur des journées qu’il découvre. « Surajusté » veut dire qu’il a un peu trop appris par cœur son historique, au lieu de dégager la tendance générale.</p>
</div>
<p>L’analyse d’<strong>importance des variables</strong> confirme la lecture métier : la variable <strong>week-end</strong> arrive en tête, suivie du <strong>jour de la semaine</strong>, puis du jour de l’année (saisonnalité). Le modèle a bien capté ce qu’un gérant sait d’instinct — les pics tombent le week-end. Un angle mort révélateur : faute de variable « jours fériés », le modèle surestime nettement le <strong>24 décembre</strong>.</p>
</section>
<section id="limites" class="level2">
<h2 class="anchored" data-anchor-id="limites">Limites</h2>
<ul>
<li><strong>Surajustement partiel</strong> — pistes de correction : plus de données d’entraînement, variables externes, ou réingénierie des résidus.</li>
<li><strong>Pas de variable « jours fériés »</strong> — d’où la surestimation du 24 décembre.</li>
<li><strong>Dépendance à une fréquence de données élevée</strong> — le même modèle sur une TPE du bâtiment, aux chantiers irréguliers, serait bien moins précis.</li>
<li><strong>Les chocs imprévisibles le restent</strong> — aucune de ces méthodes n’aurait anticipé le Covid.</li>
<li><strong>Un seuil de livraison reste à fixer</strong> — à partir de quelle MAE / RMSE un prévisionnel est-il assez fiable pour être présenté à un client ? La question se tranche <em>avant</em> la mission, pas après.</li>
</ul>
</section>
<section id="pour-aller-plus-loin" class="level2">
<h2 class="anchored" data-anchor-id="pour-aller-plus-loin">Pour aller plus loin</h2>
<p>Deux prolongements naturels : un passage en <strong>streaming</strong> — un flux continu de la caisse vers le modèle, réentraîné à fréquence maîtrisée — et une restitution <strong>Power BI</strong> : prévisions côté client, tableaux de bord de monitoring des métriques côté cabinet.</p>
<div class="travail-meta">
<p>Réalisé dans le cadre du mémoire DSCG (UE7, 2023) : « Intégration de l’intelligence artificielle au sein de l’Expertise Comptable : vers une amélioration des prévisions financières », complété par une enquête auprès de 24 experts-comptables sur leur adoption de l’IA.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/leogoose31\.github\.io\/portfolio");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Léo Gouzy · Toulouse</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="mailto:leogouzy31@gmail.com">
<p>leogouzy31@gmail.com</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.linkedin.com/in/léo-gouzy-013a65151" target="_blank">
<p>LinkedIn</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://github.com/leogoose31" target="_blank">
<p>GitHub</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>